apiVersion: v1
kind: Pod
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook

spec:
  containers:
  - name: jupyter-notebook
    image: davarski/jupyterlab-h2o:latest
    imagePullPolicy: Always
    command: ["jupyter", "lab", "--ip", "0.0.0.0"]
  
  restartPolicy: Always
