apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: saas
  namespace: saas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: saas
subjects:
  - kind: ServiceAccount
    name: saas
    namespace: saas
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: hub
  namespace: saas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hub
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: data
