stages:
  - build
  - test
  - deploy
tag_build:
  stage: build
  only:
    - tags@ds/jupyterlab-eth
  image:
    # debug version is required for shell
    name: gcr.io/kaniko-project/executor:debug-v0.10.0
    entrypoint: [""]
  script: |
    # configure kaniko
    export KCFG=$(printf '{"auths":{"%s":{"username":"%s","pass
word":"%s"}}}' \
      
"$CI_REGISTRY" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD")
    echo $KCFG > /kaniko/.docker/config.json
    /kaniko/executor --context $CI_PROJECT_DIR --dockerfile
$CI_PROJECT_DIR/Dockerfile \
    --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG \
    --destination $CI_REGISTRY_IMAGE:latest
