presto:
  environment: "production"
  workers: 1
  logLevel: "INFO"

image:
  repository: "wiwdata/presto"
  tag: "0.217"
  pullPolicy: "IfNotPresent"

service:
  type: ClusterIP

catalog:
  obj.properties: |
    connector.name=hive-hadoop2
    hive.metastore=file
    hive.metastore.catalog.dir=s3://metastore/
    hive.allow-drop-table=true
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.s3.endpoint=http://minio-service:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3select-pushdown.enabled=true

  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hive:9083
    hive.allow-drop-table=true
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.s3.endpoint=http://minio-service:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false

  mysql.properties: |
    connector.name=mysql
    connection-url=jdbc:mysql://mysql-service:3306
    connection-user=root
    connection-password=root 

coordinatorConfigs: {}
workerConfigs: {}
environmentVariables: {}
coordinatorResources: {}
workerResources: {}
coordinatorNodeSelector: {}
workerNodeSelector: {}
coordinatorTolerations: []
workerTolerations: {}
coordinatorAffinity: {}
workerAffinity: {}
